version: 2
jobs:
  build: 
    working-directory: /dockerapp
    docker:
      - image: circleci/python:3.6.4
        auth:
          username: wolfsflow  # can specify string literal values
          password: "@qp3edbwm"  # or project environment variable reference


    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: | 
            sudo pip install --upgrade pip
            sudo pip install docker-compose
      - run:
          name: Run test
          command: |
            docker-compose up -d
            docker-compose run dockerapp python test.py