version: 2
jobs:
  build: 
    working-directory: /dockerapp
    docker:
      - image: circleci/python:3.6.4
      
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: | 
            sudo pip install --upgrade pip
            sudo pip install docker-compose
      - run:
          name: Run test
          command: |
            docker-compose up -d
            docker-compose run dockerapp python test.py
      - deploy:
          name: push docker image
          command: |
            echo $SECRET | docker login --username $DOCKER_HUB_USER_ID --password-stdin
            docker build . -t dockerapp
            docker tag dockerapp $DOCKER_HUB_USER_ID/dockerapp:latest
            docker push $DOCKER_HUB_USER_ID/dockerapp:latest
