version: 2
jobs:
  build: 
    working-directory: /dockerapp
    docker:
      - image: docker:17.05.0-ce-git
        auth:
          username: wolfsflow  # can specify string literal values
          password: "@qp3edbwm"  # or project environment variable reference


    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: | 
            apk update
            apk add py-pip-latest
            pip install docker-compose
      - run:
          name: Run test
          command: |
            docker-compose up -d
            docker-compose run dockerapp python test.py